import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { LanguageClient, LanguageClientOptions, ServerOptions, TransportKind } from 'vscode-languageclient/node';
import { parseTargetFile, parseWorkspaceFile } from '../server/workspace';

let client: LanguageClient | undefined;
let statusBarItem: vscode.StatusBarItem | undefined;

export async function activate(context: vscode.ExtensionContext): Promise<void> {
  const serverModule = context.asAbsolutePath(path.join('dist', 'server.js'));

  const serverOptions: ServerOptions = {
    run: { module: serverModule, transport: TransportKind.ipc },
    debug: {
      module: serverModule,
      transport: TransportKind.ipc,
      options: { execArgv: ['--nolazy', '--inspect=6009'] }
    }
  };

  const clientOptions: LanguageClientOptions = {
    documentSelector: [{ scheme: 'file', language: 'powerbuilder' }],
    synchronize: {
      fileEvents: vscode.workspace.createFileSystemWatcher('**/*.{sra,srw,sru,srm,srd,srf,srs,srp,srq,srj}')
    }
  };

  client = new LanguageClient(
    'powerbuilderLanguageServer',
    'PowerBuilder Language Server',
    serverOptions,
    clientOptions
  );

  context.subscriptions.push(client);
  await client.start();

  // Create status bar item to show and switch PB version
  statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
  statusBarItem.command = 'powerbuilder.switchVersion';
  updateStatusBar();
  context.subscriptions.push(statusBarItem);

  // Register command to switch version
  const switchVersionCmd = vscode.commands.registerCommand('powerbuilder.switchVersion', async () => {
    const config = vscode.workspace.getConfiguration('powerbuilder');
    const currentVersion = config.get<string>('version', '2025');
    const newVersion = currentVersion === '2025' ? '2022' : '2025';

    await config.update('version', newVersion, vscode.ConfigurationTarget.Workspace);
    updateStatusBar();
    vscode.window.showInformationMessage(`PowerBuilder version switched to ${newVersion}`);
  });
  context.subscriptions.push(switchVersionCmd);

  // Watch for version changes and update status bar
  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration((e) => {
      if (e.affectsConfiguration('powerbuilder.version')) {
        updateStatusBar();
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('powerbuilder.generateOrcaScript', generateOrcaScript)
  );
}

/**
 * Generates an OrcaScript that rebuilds the workspace's PBLs from the exported
 * sources on disk (the `scc refresh target` offline pattern documented in the
 * PowerBuilder Users Guide). OrcaScript has no source-export command; source
 * export happens in the PB IDE (Git/SVN integration writes ws_objects), and
 * this script closes the loop after editing those sources in VS Code.
 */
async function generateOrcaScript(): Promise<void> {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    void vscode.window.showErrorMessage('PowerBuilder: open a workspace folder first.');
    return;
  }
  const root = folder.uri.fsPath;

  const entries = await fs.promises.readdir(root);
  const pbwName = entries.find((f) => f.toLowerCase().endsWith('.pbw'));
  if (!pbwName) {
    void vscode.window.showErrorMessage(
      'PowerBuilder: no .pbw workspace file found in the workspace root.'
    );
    return;
  }

  const pbw = parseWorkspaceFile(await fs.promises.readFile(path.join(root, pbwName), 'utf8'));
  const targets: string[] = [];
  for (const target of pbw.targets) {
    const rel = target.path.replace(/\\/g, path.sep).replace(/^\.[\\/]/, '');
    targets.push(rel);
  }
  if (targets.length === 0) {
    void vscode.window.showErrorMessage(`PowerBuilder: no targets found in ${pbwName}.`);
    return;
  }

  const lines: string[] = [
    `; OrcaScript generated by the PowerBuilder VS Code extension`,
    `; Rebuilds the PBLs of workspace "${pbwName}" from the exported sources on disk.`,
    `; Run on Windows with PowerBuilder installed:  orcascript250 ${pbwName.replace(/\.pbw$/i, '.orca')}`,
    `; (adjust the OrcaScript executable to your PB version; see`,
    `;  https://docs.appeon.com/pb2025/pbug/OrcaScript_Commands.html)`,
    '',
    'start session',
    `scc set connect property localprojpath "${root}"`,
    'scc connect offline'
  ];
  for (const target of targets) {
    const abs = path.isAbsolute(target) ? target : path.join(root, target);
    lines.push(`scc set target "${abs}" "importonly"`);
    lines.push('scc refresh target "3pass"');
    try {
      const pbt = parseTargetFile(await fs.promises.readFile(abs, 'utf8'));
      if (pbt.liblist.length > 0) {
        lines.push(`; libraries: ${pbt.liblist.join(', ')}`);
      }
    } catch {
      lines.push(`; warning: target file not readable: ${abs}`);
    }
  }
  lines.push('scc close', 'end session', '');

  const outPath = path.join(root, pbwName.replace(/\.pbw$/i, '.orca'));
  await fs.promises.writeFile(outPath, lines.join('\n'), 'utf8');
  const doc = await vscode.workspace.openTextDocument(outPath);
  await vscode.window.showTextDocument(doc);
  void vscode.window.showInformationMessage(
    `PowerBuilder: wrote ${path.basename(outPath)} (${targets.length} target(s)).`
  );
}

function updateStatusBar(): void {
  if (!statusBarItem) {
    return;
  }

  const config = vscode.workspace.getConfiguration('powerbuilder');
  const version = config.get<string>('version', '2025');
  statusBarItem.text = `$(settings) PB ${version}`;
  statusBarItem.tooltip = 'Click to switch PowerBuilder version (2022 ↔ 2025)';
  statusBarItem.show();
}

export async function deactivate(): Promise<void> {
  if (client) {
    await client.stop();
  }
}
